{
 "title": "Flask Api",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Request Latency (Average, Max, Min) - With Cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(request_duration_seconds_with_cache_sum[5m])",
     "legendFormat": "Avg Latency with Cache"
    },
    {
     "expr": "max_over_time(request_duration_seconds_with_cache_sum[5m])",
     "legendFormat": "Max Latency with Cache"
    },
    {
     "expr": "min_over_time(request_duration_seconds_with_cache_sum[5m])",
     "legendFormat": "Min Latency with Cache"
    }
   ]
  },
  {
   "title": "Request Latency (Average, Max, Min) - Without Cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(request_duration_seconds_without_cache_sum[5m])",
     "legendFormat": "Avg Latency without Cache"
    },
    {
     "expr": "max_over_time(request_duration_seconds_without_cache_sum[5m])",
     "legendFormat": "Max Latency without Cache"
    },
    {
     "expr": "min_over_time(request_duration_seconds_without_cache_sum[5m])",
     "legendFormat": "Min Latency without Cache"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "sum(cache_hits_total)", "legendFormat": "Cache Hits" }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(cache_misses_total)", "legendFormat": "Cache Misses" }
   ]
  }
 ]
}