{
 "title": "Ingest Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cantidad de objetos procesados",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(processed_objects_total)", "legendFormat": "Total objetos procesados" }
   ]
  },
  {
   "title": "Cantidad de filas procesadas",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "sum(processed_rows_total)", "legendFormat": "Total filas procesadas" }
   ]
  },
  {
   "title": "Cantidad de filas con error",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(error_rows_total)", "legendFormat": "Total filas con error" }
   ]
  },
  {
   "title": "Tiempo de procesamiento de un objeto (Max, Min, Promedio)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg_over_time(object_processing_time_seconds_sum[5m])",
     "legendFormat": "Promedio"
    },
    {
     "expr": "max_over_time(object_processing_time_seconds_sum[5m])",
     "legendFormat": "Máximo"
    },
    {
     "expr": "min_over_time(object_processing_time_seconds_sum[5m])",
     "legendFormat": "Mínimo"
    }
   ]
  },
  {
   "title": "Tiempo de procesamiento de una fila (Max, Min, Promedio)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(row_processing_time_seconds_sum[5m])",
     "legendFormat": "Promedio"
    },
    {
     "expr": "max_over_time(row_processing_time_seconds_sum[5m])",
     "legendFormat": "Máximo"
    },
    {
     "expr": "min_over_time(row_processing_time_seconds_sum[5m])",
     "legendFormat": "Mínimo"
    }
   ]
  }
 ]
}