config:
  docker_registry: juand0908
  flask:
    replicas: 2 
    name: flask
    image: api
  ui:
    replicas: 1 
    name: ui
    image: ui
    port: 80
    targetPort: 80
    nodePort: 32000 