config:
  docker_registry: alexnaranjo24
  access_key: AKIAQ2VOGXQDTWAX4PUY
  secret_key: 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
  bucket: 2024-02-ic4302-gr1
  producer:
    replicas: 2 
    name: ingest
    image: ingest
  consumer:
    replicas: 2
    name: hugging-face-api
    image: hugging-face-api
  debug:
    replicas: 1
    name: debug
    image: s3crawler
  cronjob:
    name: s3crawler
    image: s3crawler
    schedule: "0/5 * * * *"
  flask:
    replicas: 2
    name: flask-api
    image: flask-api
  service:
    name: ui
    image: ui
    replicas: 2
    port: 80
    targetPort: 80
    nodePort: 32000