apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.loader.name }}-job
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.config.loader.name }}
        volumeMounts:
          - mountPath: "/data"
            name: data  # Se refiere al volumen que definimos más abajo
        image: {{ .Values.config.docker_registry }}/{{ .Values.config.loader.image }}  # Utiliza el registro y la imagen definidos en values.yaml
        env:
        - name: XPATH
          value: "/data"
        - name: postgre_host
          value: "databases-postgresql"
        - name: postgre_user
          value: "user"
        - name: postgre_password
          value: "1234"
        - name: postgre_dbname
          value: "LyricsDB"
        - name: postgre_port
          value: "5432"
        - name: mongo_client
          value: "mongodb+srv://AlexNaranjo:S4vpz219@cluster0.vqij1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/formal-incline-431300-v8-b810b4ffbab6.json"  # Ruta del archivo JSON en la carpeta app
      restartPolicy: Never
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
  backoffLimit: 4
