apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.cronjob.name }}
spec:
  schedule: {{ .Values.config.cronjob.schedule }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: data
          - name: scripts
            configMap:
              name: scala
              defaultMode: 0700
          containers:
            - image: {{ .Values.config.docker_registry }}/{{ .Values.config.cronjob.image }}
              name: {{ .Values.config.cronjob.name }}
              env:
                - name: BUCKET
                  value: "2024-02-ic4302-gr1"
                - name: ACCESS_KEY
                  value: "AKIAQ2VOGXQDTWAX4PUY"
                - name: SECRET_KEY
                  value: "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"
                - name: PREFIX
                  value: "spotify/"
                - name: RABBITMQ
                  value: "databases-rabbitmq"
                - name: RABBITMQ_QUEUE
                  value: "queue"
                - name: RABBITMQ_USER
                  value: "user"
                - name: XPATH
                  value: "/data"
                - name: RABBITMQ_PASS
                  valueFrom:
                    secretKeyRef:
                      name: databases-rabbitmq
                      key: rabbitmq-password
                      optional: false
                - name: XPATH
                  value: "/data"
                - name: ELASTIC_USER
                  value: "elastic"
                - name: ELASTIC_PASS
                  valueFrom:
                    secretKeyRef:
                      name: ic4302-es-elastic-user
                      key: elastic
                      optional: false
                - name: ELASTIC
                  value: "ic4302-es-http"
              volumeMounts:
                - mountPath: "/data"
                  name: data
                - name: scripts
                  mountPath: /scripts