apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.consumer.name }}  # Toma el nombre de values.yaml
spec:
  replicas: {{ .Values.config.consumer.replicas }}  # Define el número de réplicas (en este caso, 2)
  selector:
    matchLabels:
      app: {{ .Values.config.consumer.name }}  # Selector para identificar los pods correctos
  template:
    metadata:
      labels:
        app: {{ .Values.config.consumer.name }}
    spec:
      containers:
      - name: {{ .Values.config.consumer.name }}
        image: "{{ .Values.docker_registry }}/{{ .Values.config.consumer.image }}"  # Imagen desde values.yaml
        ports:
        - containerPort: 5000  # Puerto en el que corre tu API

apiVersion: v1
kind: Service
metadata:
  name: hugging-face-api-nodeport
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000  # Cambiado a 5000 para coincidir con Flask
      targetPort: 5000  # Cambiado a 5000 para coincidir con Flask
  selector:
    app: hugging-face-api
  type: NodePort