apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.service.name }}-nodeport
  namespace: default
spec:
  selector:
    app: {{ .Values.config.service.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.config.service.port }}
      targetPort: {{ .Values.config.service.targetPort }}
      {{- if .Values.config.service.nodePort }}
      nodePort: {{ .Values.config.service.nodePort }}  # El campo nodePort debe estar aquí, dentro del bloque de puertos
      {{- end }}
  type: NodePort